language: node_js

node_js:
  - node
  - '8'
  - '6'

install:
  - sudo apt-get install -y libboost-dev libsndfile1-dev
  - wget https://github.com/csound/csound/archive/6.09.1.tar.gz
  - tar -xf 6.09.1.tar.gz
  - mkdir csound
  - cd csound
  - cmake ../csound-6.09.1
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - npm install csound-api

before_script:
  - npm --global install jasmine
  - npm install dedent-js
  - cd lib/csound-parser

script:
  - jasmine
