# https://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: Current
    - nodejs_version: '11'
    - nodejs_version: LTS
    - nodejs_version: '8'

install:
  # Remove large directories to stay below AppVeyor’s disk usage quota.
  - rd C:\cygwin /s /q
  - rd C:\Qt /s /q
  # Install Node.js.
  - ps: Install-Product node $Env:nodejs_version x64
  # Install Csound; see https://www.appveyor.com/docs/how-to/download-file.
  - ps: Start-FileDownload 'https://github.com/csound/csound/releases/download/6.12.2/Csound6.12.0-Windows_x64-installer.exe'
  - ps: Start-Process 'Csound6.12.0-Windows_x64-installer.exe' '/verySilent /noRestart' -Wait
  - set PATH=%PATH%;%ProgramFiles%\Csound6_x64\bin
  # Install csound-api.
  - set CL=/I"C:\Libraries\boost_1_69_0" /I"%ProgramFiles%\Csound6_x64\include"
  - set LINK="%ProgramFiles%\Csound6_x64\lib\csound64.lib"
  - npm install csound-api

test_script:
  - npm --global install jasmine
  - npm install dedent-js
  - cd lib\csound-parser
  - jasmine

build: off
