# https://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: Stable
    - nodejs_version: LTS
    - nodejs_version: '6'

install:
  # Install Node.js.
  - ps: Install-Product node $env:nodejs_version x64
  # Install Csound; see https://www.appveyor.com/docs/how-to/download-file.
  - ps: Start-FileDownload 'https://github.com/csound/csound/releases/download/6.10.0/csound-windows-x64-6.10.0.exe'
  - ps: Start-Process 'csound-windows-x64-6.10.0.exe' -ArgumentList '/verySilent', '/noRestart' -Wait
  - set PATH=%PATH%;%ProgramFiles%\csound-windows-x64\bin
  # Install csound-api.
  - set CL=/I"C:\Libraries\boost_1_63_0" /I"C:\Program Files\csound-windows-x64\include"
  - set LINK="C:\Program Files\csound-windows-x64\lib\csound64.lib"
  - npm install csound-api

test_script:
  - npm --global install jasmine
  - npm install dedent-js
  - cd lib\csound-parser
  - jasmine

build: off
