/* generated by jison-lex 0.3.4-131 */
var preprocessor = (function () {
// See also:
// http://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript/#35881508
// but we keep the prototype.constructor and prototype.name assignment lines too for compatibility
// with userland code which might access the derived class in a 'classic' way.
function JisonLexerError(msg, hash) {
    Object.defineProperty(this, 'name', {
        enumerable: false,
        writable: false,
        value: 'JisonLexerError'
    });

    if (msg == null) msg = '???';

    Object.defineProperty(this, 'message', {
        enumerable: false,
        writable: true,
        value: msg
    });

    this.hash = hash;

    var stacktrace;
    if (hash && hash.exception instanceof Error) {
        var ex2 = hash.exception;
        this.message = ex2.message || msg;
        stacktrace = ex2.stack;
    }
    if (!stacktrace) {
        if (Error.hasOwnProperty('captureStackTrace')) { // V8
            Error.captureStackTrace(this, this.constructor);
        } else {
            stacktrace = (new Error(msg)).stack;
        }
    }
    if (stacktrace) {
        Object.defineProperty(this, 'stack', {
            enumerable: false,
            writable: false,
            value: stacktrace
        });
    }
}

    if (typeof Object.setPrototypeOf === 'function') {
        Object.setPrototypeOf(JisonLexerError.prototype, Error.prototype);
    } else {
        JisonLexerError.prototype = Object.create(Error.prototype);
    }
    JisonLexerError.prototype.constructor = JisonLexerError;
    JisonLexerError.prototype.name = 'JisonLexerError';


var lexer = {

EOF:1,

ERROR:2,

parseError:function lexer_parseError(str, hash) {
        if (this.yy.parser && typeof this.yy.parser.parseError === 'function') {
            return this.yy.parser.parseError(str, hash) || this.ERROR;
        } else {
            throw new this.JisonLexerError(str);
        }
    },

// resets the lexer, sets new input
setInput:function lexer_setInput(input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this._signaled_error_token = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0, 0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function lexer_input() {
        if (!this._input) {
            this.done = true;
            return null;
        }
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        // Count the linenumber up when we hit the LF (or a stand-alone CR).
        // On CRLF, the linenumber is incremented when you fetch the CR or the CRLF combo
        // and we advance immediately past the LF as well, returning both together as if
        // it was all a single 'character' only.
        var slice_len = 1;
        var lines = false;
        if (ch === '\n') {
            lines = true;
        } else if (ch === '\r') {
            lines = true;
            var ch2 = this._input[1];
            if (ch2 === '\n') {
                slice_len++;
                ch += ch2;
                this.yytext += ch2;
                this.yyleng++;
                this.offset++;
                this.match += ch2;
                this.matched += ch2;
                if (this.options.ranges) {
                    this.yylloc.range[1]++;
                }
            }
        }
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(slice_len);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function lexer_unput(ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - len);
        this.matched = this.matched.substr(0, this.matched.length - len);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }

        this.yylloc.last_line = this.yylineno + 1;
        this.yylloc.last_column = (lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                + oldLines[oldLines.length - lines.length].length - lines[0].length :
                this.yylloc.first_column - len);

        if (this.options.ranges) {
            this.yylloc.range[1] = this.yylloc.range[0] + this.yyleng - len;
        }
        this.yyleng = this.yytext.length;
        this.done = false;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function lexer_more() {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function lexer_reject() {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            // when the parseError() call returns, we MUST ensure that the error is registered.
            // We accomplish this by signaling an 'error' token to be produced for the current
            // .lex() run.
            this._signaled_error_token = (this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: this.match,
                token: null,
                line: this.yylineno,
                loc: this.yylloc,
                lexer: this
            }) || this.ERROR);
        }
        return this;
    },

// retain first n characters of the match
less:function lexer_less(n) {
        this.unput(this.match.slice(n));
    },

// return (part of the) already matched input, i.e. for error messages
pastInput:function lexer_pastInput(maxSize) {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        if (maxSize < 0)
            maxSize = past.length;
        else if (!maxSize)
            maxSize = 20;
        return (past.length > maxSize ? '...' + past.substr(-maxSize) : past);
    },

// return (part of the) upcoming input, i.e. for error messages
upcomingInput:function lexer_upcomingInput(maxSize) {
        var next = this.match;
        if (maxSize < 0)
            maxSize = next.length + this._input.length;
        else if (!maxSize)
            maxSize = 20;
        if (next.length < maxSize) {
            next += this._input.substr(0, maxSize - next.length);
        }
        return (next.length > maxSize ? next.substr(0, maxSize) + '...' : next);
    },

// return a string which displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function lexer_showPosition() {
        var pre = this.pastInput().replace(/\s/g, ' ');
        var c = new Array(pre.length + 1).join('-');
        return pre + this.upcomingInput().replace(/\s/g, ' ') + '\n' + c + '^';
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function lexer_test_match(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset + this.yyleng];
        }
        this.offset += this.yyleng;
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        } else if (this._signaled_error_token) {
            // produce one 'error' token as .parseError() in reject() did not guarantee a failure signal by throwing an exception!
            token = this._signaled_error_token;
            this._signaled_error_token = false;
            return token;
        }
        return false;
    },

// return next match in input
next:function lexer_next() {
        function clear() {
            this.yytext = '';
            this.yyleng = 0;
            this.match = '';
            this.matches = false;
            this._more = false;
            this._backtrack = false;
        }

        if (this.done) {
            clear.call(this);
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            clear.call(this);
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === '') {
            clear.call(this);
            this.done = true;
            return this.EOF;
        } else {
            token = this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: this.match + this._input,
                token: null,
                line: this.yylineno,
                loc: this.yylloc,
                lexer: this
            }) || this.ERROR;
            if (token === this.ERROR) {
                // we can try to recover from a lexer error that parseError() did not 'recover' for us, by moving forward at least one character at a time:
                if (!this.match.length) {
                    this.input();
                }
            }
            return token;
        }
    },

// return next match that has a token
lex:function lexer_lex() {
        var r;
        // allow the PRE/POST handlers set/modify the return token for maximum flexibility of the generated lexer:
        if (typeof this.options.pre_lex === 'function') {
            r = this.options.pre_lex.call(this);
        }
        while (!r) {
            r = this.next();
        }
        if (typeof this.options.post_lex === 'function') {
            // (also account for a userdef function which does not return any value: keep the token as is)
            r = this.options.post_lex.call(this, r) || r;
        }
        return r;
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function lexer_begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function lexer_popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function lexer__currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions['INITIAL'].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function lexer_topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return 'INITIAL';
        }
    },

// alias for begin(condition)
pushState:function lexer_pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function lexer_stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
JisonLexerError: JisonLexerError,
performAction: function anonymous(yy, yy_, $avoiding_name_collisions, YY_START) {

var YYSTATE = YY_START;
switch($avoiding_name_collisions) {
case 0 : 
/*! Conditions:: INITIAL quoted_string */ 
/*! Rule::       {line_continuation} */ 
 
  this.currentTextNode = null;
  for (let i = yy_.yyleng - 1; i > 0; i--) {
    // TODO: const character
    var character = yy_.yytext.charAt(i);
    if (character !== '\n' && character !== '\r') {
      this.messages.push({
        type: 'Warning',
        filePath: this.filePath,
        text: 'Line continuation is not followed immediately by newline',
        range: [
          [yy_.yylloc.first_line - 1, yy_.yylloc.first_column],
          [yy_.yylloc.first_line - 1, yy_.yylloc.first_column + 1]
        ]
      });
      break;
    }
  }
 
break;
case 1 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       \/\* */ 
 
  this.begin('block_comment');
  this.startRanges.push(this.rangeFromLocation(yy_.yylloc));
  this.addText(' ');
 
break;
case 2 : 
/*! Conditions:: block_comment */ 
/*! Rule::       \/\* */ 
 
  this.messages.push({
    type: 'Warning',
    filePath: this.filePath,
    text: `${this.quote(yy_.yytext)} in block comment`,
    range: this.rangeFromLocation(yy_.yylloc)
  });
 
break;
case 3 : 
/*! Conditions:: block_comment */ 
/*! Rule::       \*\/ */ 
 
  this.startRanges.pop();
  this.popState();
 
break;
case 4 : 
/*! Conditions:: block_comment */ 
/*! Rule::       .|{newline} */ 
 // Do nothing 
break;
case 5 : 
/*! Conditions:: block_comment */ 
/*! Rule::       $ */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: 'Unterminated block comment',
    range: this.startRanges.pop()
  });
 
break;
case 6 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       {single_line_comment} */ 
 this.addNewline(); 
break;
case 7 : 
/*! Conditions:: quoted_string braced_string */ 
/*! Rule::       \\[^abfnrtv"\\\\] */ 
 
  this.addText(yy_.yytext);
  this.messages.push({
    type: 'Warning',
    filePath: this.filePath,
    text: `Unknown escape sequence ${this.quote(yy_.yytext)}`,
    range: this.rangeFromLocation(yy_.yylloc)
  });
 
break;
case 8 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       " */ 
 
  this.begin('quoted_string');
  this.startRanges.push(this.rangeFromLocation(yy_.yylloc));
  this.addText(yy_.yytext);
 
break;
case 9 : 
/*! Conditions:: quoted_string */ 
/*! Rule::       \\.|[^$"\n\r] */ 
 this.addText(yy_.yytext); 
break;
case 10 : 
/*! Conditions:: quoted_string */ 
/*! Rule::       " */ 
 
  this.startRanges.pop();
  this.popState();
  this.addText(yy_.yytext);
 
break;
case 11 : 
/*! Conditions:: quoted_string */ 
/*! Rule::       {newline}|$ */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: `Missing terminating ${this.quote('"')}`,
    range: this.startRanges.pop()
  });
 
break;
case 12 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       \{\{ */ 
 
  this.begin('braced_string');
  this.startRanges.push(this.rangeFromLocation(yy_.yylloc));
  this.addText(yy_.yytext);
 
break;
case 13 : 
/*! Conditions:: braced_string */ 
/*! Rule::       (?:[^}]|\}[^}])+ */ 
 this.addText(yy_.yytext); 
break;
case 14 : 
/*! Conditions:: braced_string */ 
/*! Rule::       \}\} */ 
 
  this.startRanges.pop();
  this.popState();
  this.addText(yy_.yytext);
 
break;
case 15 : 
/*! Conditions:: braced_string */ 
/*! Rule::       $ */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: `Missing terminating ${this.quote('}}')}`,
    range: this.startRanges.pop()
  });
 
break;
case 16 : 
/*! Conditions:: INITIAL quoted_string */ 
/*! Rule::       {macro_use}\( */ 
 
  let i = yy_.yyleng - 2;
  if (yy_.yytext.charAt(i) === '.') {
    this.messages.push({
      type: 'Warning',
      filePath: this.filePath,
      text: `Unnecessary ${this.quote('.')} after macro name`,
      range: [
        [yy_.yylloc.first_line - 1, yy_.yylloc.first_column + i],
        [yy_.yylloc.first_line - 1, yy_.yylloc.first_column + i + 1]
      ]
    });
  } else {
    i++;
  }
  this.macroUse = new MacroUseElement(this.getMacro(yy_.yytext.substring(1, i)));
  this.begin('macro_parameter_value_list');
 
break;
case 17 : 
/*! Conditions:: macro_parameter_value_list */ 
/*! Rule::       [^'#)]+ */ 
 
  {
    this.begin('after_macro_parameter_value');
    const macrosByName = this.macroUse.macrosByName;
    const parameterNameIndex = Object.keys(macrosByName).length;
    // TODO: const macro
    var macro = this.macroUse.macro;
    if (parameterNameIndex >= macro.parameterNames.length) {
      throw new CsoundPreprocessorError({
        type: 'Error',
        filePath: this.filePath,
        text: 'Too many arguments provided to function-like macro',
        range: this.rangeFromLocation(yy_.yylloc),
        trace: [{
          type: 'Trace',
          filePath: this.filePath,
          text: `Macro ${this.quote(macro.name)} defined here`,
          range: macro.range
        }]
      });
    }
    const macroName = macro.parameterNames[parameterNameIndex];
    macrosByName[macroName] = {
      name: macroName,
      body: yy_.yytext
    };
  }
 
break;
case 18 : 
/*! Conditions:: after_macro_parameter_value */ 
/*! Rule::       \) */ 
 
  this.popState();
  this.popState();
  this.expandMacro(YY_START);
 
break;
case 19 : 
/*! Conditions:: INITIAL quoted_string */ 
/*! Rule::       {macro_use} */ 
 
  {
    let i = yy_.yyleng - 1;
    if (yy_.yytext.charAt(i) === '.') {
      // TODO: const character
      var character = this.input();
      this.unput(character);
      // This needs to be kept synchronized with the macro name pattern.
      if (!/\w/.test(character)) {
        this.messages.push({
          type: 'Warning',
          filePath: this.filePath,
          text: `Unnecessary ${this.quote('.')} after macro name`,
          range: [
            [yy_.yylloc.first_line - 1, yy_.yylloc.first_column + i],
            [yy_.yylloc.first_line - 1, yy_.yylloc.first_column + i + 1]
          ]
        });
      }
    } else {
      i++;
    }
    this.macroUse = new MacroUseElement(this.getMacro(yy_.yytext.substring(1, i)));
    this.expandMacro(YY_START);
  }
 
break;
case 20 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       {define} */ 
 
  this.begin('define_directive');
  this.startRanges.push(this.rangeFromLocation(yy_.yylloc));
  this.sourceRange = {location: this.matched.length - yy_.yytext.length};
 
break;
case 21 : 
/*! Conditions:: define_directive */ 
/*! Rule::       {identifier}\(? */ 
 
  this.popState();
  const newMacro = {body: ''};
  const lastCharacterIndex = yy_.yyleng - 1;
  if (yy_.yytext.charAt(lastCharacterIndex) === '(') {
    this.begin('macro_parameter_name_list');
    this.startRanges.push([
      [yy_.yylloc.last_line - 1, yy_.yylloc.last_column - 1],
      [yy_.yylloc.last_line - 1, yy_.yylloc.last_column]
    ]);
    newMacro.name = yy_.yytext.substr(0, lastCharacterIndex);
    newMacro.parameterNames = [];
    newMacro.range = [
      [yy_.yylloc.first_line - 1, yy_.yylloc.first_column],
      [yy_.yylloc.last_line - 1, yy_.yylloc.last_column - 1]
    ];
  } else {
    this.begin('before_macro_body');
    newMacro.name = yy_.yytext;
    newMacro.range = this.rangeFromLocation(yy_.yylloc);
  }
  // TODO: const macro
  var macro = this.macrosByName[newMacro.name];
  if (macro) {
    // TODO: const message
    var message = {
      type: 'Warning',
      filePath: this.filePath,
      text: `${this.quote(newMacro.name)} macro redefined`,
      range: newMacro.range
    };
    if (macro.range) {
      message.trace = [{
        type: 'Trace',
        filePath: this.filePath,
        text: 'Previous definition is here',
        range: macro.range
      }];
    } else {
      message.text += `, was ${this.quote(macro.body)}`;
    }
    this.messages.push(message);
  }
  this.macro = newMacro;
  this.macrosByName[newMacro.name] = newMacro;
 
break;
case 22 : 
/*! Conditions:: define_directive */ 
/*! Rule::       \s+ */ 
 // Do nothing 
break;
case 23 : 
/*! Conditions:: macro_parameter_name_list after_macro_parameter_name_separator */ 
/*! Rule::       {identifier} */ 
 
  const parameterNames = this.macro.parameterNames;
  if (parameterNames.indexOf(yy_.yytext) >= 0) {
    throw new CsoundPreprocessorError({
      type: 'Error',
      filePath: this.filePath,
      text: `Duplicate macro parameter name ${this.quote(yy_.yytext)}`,
      range: this.rangeFromLocation(yy_.yylloc)
    });
  }
  parameterNames.push(yy_.yytext);
  if ('after_macro_parameter_name_separator' === YY_START)
    this.popState();
  this.begin('after_macro_parameter_name');
 
break;
case 24 : 
/*! Conditions:: macro_parameter_name_list macro_parameter_value_list */ 
/*! Rule::       \) */ 
 
  this.startRanges.pop();
  if ('macro_parameter_name_list' === this.popState())
    this.begin('before_macro_body');
 
break;
case 25 : 
/*! Conditions:: macro_parameter_name_list after_macro_parameter_name_separator */ 
/*! Rule::       \s+ */ 
 // Do nothing 
break;
case 26 : 
/*! Conditions:: macro_parameter_name_list after_macro_parameter_name_separator */ 
/*! Rule::       . */ 
 
  throw new CsoundPreprocessorError({
    type: 'Error',
    filePath: this.filePath,
    text: 'Expected macro parameter name',
    range: this.rangeFromPosition(yy_.yylloc.first_line, yy_.yylloc.first_column)
  });
 
break;
case 27 : 
/*! Conditions:: macro_parameter_name_list */ 
/*! Rule::       $ */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: `Missing terminating ${this.quote(')')}`,
    range: this.startRanges.pop()
  });
 
break;
case 28 : 
/*! Conditions:: after_macro_parameter_name after_macro_parameter_value */ 
/*! Rule::       ['#] */ 
 
  if (yy_.yytext !== "'") {
    this.messages.push({
      type: 'Warning',
      filePath: this.filePath,
      text: `${this.quote(yy_.yytext)} instead of single quote used to separate macro parameters`,
      range: this.rangeFromLocation(yy_.yylloc)
    });
  }
  if ('after_macro_parameter_name' === this.popState())
    this.begin('after_macro_parameter_name_separator');
 
break;
case 29 : 
/*! Conditions:: after_macro_parameter_name after_macro_parameter_value */ 
/*! Rule::       \) */ 
 
  const wasAfterMacroParameterName = 'after_macro_parameter_name' === this.popState();
  this.popState();
  if (wasAfterMacroParameterName)
    this.begin('before_macro_body');
 
break;
case 30 : 
/*! Conditions:: after_macro_parameter_name */ 
/*! Rule::       \s+ */ 
 // Do nothing 
break;
case 31 : 
/*! Conditions:: after_macro_parameter_name */ 
/*! Rule::       . */ 
 
  throw new CsoundPreprocessorError({
    type: 'Error',
    filePath: this.filePath,
    text: 'Expected single quote in macro parameter list',
    range: this.rangeFromPosition(yy_.yylloc.first_line, yy_.yylloc.first_column)
  });
 
break;
case 32 : 
/*! Conditions:: before_macro_body */ 
/*! Rule::       # */ 
 
  this.popState();
  this.begin('macro_body');
  this.startRanges.push(this.rangeFromLocation(yy_.yylloc));
 
break;
case 33 : 
/*! Conditions:: before_macro_body */ 
/*! Rule::       \s+ */ 
 // Do nothing 
break;
case 34 : 
/*! Conditions:: before_macro_body */ 
/*! Rule::       [^#]|$ */ 
 
  // TODO: const message
  var message = {
    type: 'Error',
    filePath: this.filePath,
    text: `Expected ${this.quote('#')} after macro name`,
    range: this.rangeFromPosition(yy_.yylloc.first_line, yy_.yylloc.first_column)
  };
  if (yy_.yytext.length > 0)
    throw new CsoundPreprocessorError(message);
  this.messages.push(message);
 
break;
case 35 : 
/*! Conditions:: macro_body */ 
/*! Rule::       (\\#|[^#])+ */ 
 this.macro.body = yy_.yytext; 
break;
case 36 : 
/*! Conditions:: macro_body */ 
/*! Rule::       # */ 
 
  this.startRanges.pop();
  this.popState();
  this.sourceRange.length = this.matched.length - this.sourceRange.location;
  this.addText(' ', this.sourceRange);
 
break;
case 37 : 
/*! Conditions:: macro_body */ 
/*! Rule::       $ */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: `Missing terminating ${this.quote('#')}`,
    range: this.startRanges.pop()
  });
 
break;
case 38 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       {undef} */ 
 
  this.begin('undef_directive');
  this.startRanges.push(this.rangeFromLocation(yy_.yylloc));
 
break;
case 39 : 
/*! Conditions:: undef_directive */ 
/*! Rule::       {identifier} */ 
 
  this.startRanges.pop();
  this.popState();
  if (this.macrosByName[yy_.yytext]) {
    delete this.macrosByName[yy_.yytext];
  } else {
    this.messages.push({
      type: 'Error',
      filePath: this.filePath,
      text: `${this.quote(yy_.yytext)} macro is not defined`,
      range: this.rangeFromLocation(yy_.yylloc)
    });
  }
 
break;
case 40 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       {ifdef_or_ifndef} */ 
 
  this.begin(yy_.yytext.startsWith('#ifdef') ? 'ifdef_directive' : 'ifndef_directive');
  this.startRanges.push(this.rangeFromLocation(yy_.yylloc));
 
break;
case 41 : 
/*! Conditions:: ifdef_directive */ 
/*! Rule::       {identifier} */ 
 this.popState(); this.begin(this.macrosByName[yy_.yytext] ? 'ifdef_true' : 'ifdef_false'); 
break;
case 42 : 
/*! Conditions:: ifndef_directive */ 
/*! Rule::       {identifier} */ 
 this.popState(); this.begin(!this.macrosByName[yy_.yytext] ? 'ifdef_true' : 'ifdef_false'); 
break;
case 43 : 
/*! Conditions:: ifdef_true ifdef_false else_true else_false */ 
/*! Rule::       {endif} */ 
 
  this.startRanges.pop();
  this.popState();
 
break;
case 44 : 
/*! Conditions:: else_true else_false */ 
/*! Rule::       {else} */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: '#else after #else',
    range: this.rangeFromLocation(yy_.yylloc)
  });
 
break;
case 45 : 
/*! Conditions:: ifdef_true */ 
/*! Rule::       {else} */ 
 this.popState(); this.begin('else_false'); 
break;
case 46 : 
/*! Conditions:: ifdef_false */ 
/*! Rule::       {else} */ 
 this.popState(); this.begin('else_true'); 
break;
case 47 : 
/*! Conditions:: ifdef_false else_false */ 
/*! Rule::       .|{newline} */ 
 // Do nothing 
break;
case 48 : 
/*! Conditions:: ifdef_true ifdef_false else_true else_false */ 
/*! Rule::       $ */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: 'Unterminated conditional directive',
    range: this.startRanges.pop()
  });
 
break;
case 49 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       {endif} */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: `${yy_.yytext} without #ifdef or #ifndef`,
    range: this.rangeFromLocation(yy_.yylloc)
  });
 
break;
case 50 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       {else} */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: '#else without #ifdef or #ifndef',
    range: this.rangeFromLocation(yy_.yylloc)
  });
 
break;
case 51 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       {include} */ 
 
  this.begin('include_directive');
  this.startRanges.push(this.rangeFromLocation(yy_.yylloc));
 
break;
case 52 : 
/*! Conditions:: include_directive */ 
/*! Rule::       [ \t] */ 
 // Do nothing 
break;
case 53 : 
/*! Conditions:: include_directive */ 
/*! Rule::       [^ \t] */ 
 
  {
    const includeRange = this.rangeFromPosition(yy_.yylloc.first_line, yy_.yylloc.first_column);
    const delimiter = yy_.yytext;
    if (delimiter !== '"') {
      this.messages.push({
        type: 'Warning',
        filePath: this.filePath,
        text: `${this.quote(delimiter)} instead of ${this.quote('"')} used to enclose file path`,
        range: includeRange
      });
    }
    let includeFilePath = '';
    // TODO: let character
    for (var character = this.input(); character !== delimiter; character = this.input()) {
      if (character === '\n' || character === '\r' || !character) {
        throw new CsoundPreprocessorError({
          type: 'Error',
          filePath: this.filePath,
          text: `Missing terminating ${this.quote(delimiter)}`,
          range: includeRange
        });
      }
      includeFilePath += character;
    }
    this.popState();
    if (includeFilePath.length > 0) {
      let paths = [];
      if (path.isAbsolute(includeFilePath)) {
        paths.push(includeFilePath);
      } else {
        // From https://csound.github.io/docs/manual/OrchDirFiles.html, first
        // search the current directory, then the directory of the file being
        // preprocessed. TODO: Then search the directories in INCDIR.
        paths.push(path.resolve());
        if (this.filePath)
          paths.push(path.dirname(this.filePath));
        paths = paths.map(directory => path.join(directory, includeFilePath));
      }
      for (const absolutePath of paths) {
        let stats;
        try {
          stats = fs.statSync(absolutePath);
        } catch (error) {
          continue;
        }
        if (stats.isFile()) {
          if (this.includeDepth === this.maximumIncludeDepth) {
            throw new CsoundPreprocessorError({
              type: 'Error',
              filePath: this.filePath,
              text: '#include nested too deeply',
              range: includeRange
            });
          }
          const preprocessor = this.makePreprocessor(fs.readFileSync(absolutePath, 'utf8'));
          preprocessor.filePath = absolutePath;
          preprocessor.includeDepth = this.includeDepth + 1;
          preprocessor.lex();
          for (const childNode of preprocessor.rootElement.childNodes) {
            this.rootElement.childNodes.push(childNode);
          }
          this.currentTextNode = null;
          return;
        }
      }
      throw new CsoundPreprocessorError({
        type: 'Error',
        filePath: this.filePath,
        text: `${this.quote(includeFilePath)} file not found`,
        range: includeRange
      });
    } else {
      this.messages.push({
        type: 'Warning',
        filePath: this.filePath,
        text: 'Empty file path',
        range: includeRange
      });
    }
  }
 
break;
case 54 : 
/*! Conditions:: include_directive */ 
/*! Rule::       {newline}|$ */ 
 
  throw new CsoundPreprocessorError({
    type: 'Error',
    filePath: this.filePath,
    text: 'File path missing',
    range: this.startRanges.pop()
  });
 
break;
case 55 : 
/*! Conditions:: define_directive undef_directive ifdef_directive ifndef_directive */ 
/*! Rule::       \s+ */ 
 // Do nothing 
break;
case 56 : 
/*! Conditions:: define_directive undef_directive ifdef_directive ifndef_directive */ 
/*! Rule::       [^\s] */ 
 
  throw new CsoundPreprocessorError({
    type: 'Error',
    filePath: this.filePath,
    text: 'Macro name must be an identifier',
    range: this.rangeFromPosition(yy_.yylloc.first_line, yy_.yylloc.first_column)
  });
 
break;
case 57 : 
/*! Conditions:: define_directive undef_directive ifdef_directive ifndef_directive */ 
/*! Rule::       $ */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: 'Macro name missing',
    range: this.startRanges.pop()
  });
 
break;
case 58 : 
/*! Conditions:: INITIAL macro_parameter_value_list */ 
/*! Rule::       @ */ 
 this.begin('next_power_of_2'); 
break;
case 59 : 
/*! Conditions:: next_power_of_2 */ 
/*! Rule::       @ */ 
 this.popState(); this.begin('next_power_of_2_plus_1'); 
break;
case 60 : 
/*! Conditions:: next_power_of_2 */ 
/*! Rule::       \d+ */ 
 
  this.popState();
  this.addText(Math.pow(2, Math.ceil(Math.log2(Number(yy_.yytext) + 1))).toString());
 
break;
case 61 : 
/*! Conditions:: next_power_of_2_plus_1 */ 
/*! Rule::       \d+ */ 
 
  this.popState();
  this.addText((yy_.yytext === '0') ? '2' : (Math.pow(2, Math.ceil(Math.log2(Number(yy_.yytext)))) + 1).toString());
 
break;
case 62 : 
/*! Conditions:: next_power_of_2 next_power_of_2_plus_1 */ 
/*! Rule::       [ \t]+ */ 
 
  this.messages.push({
    type: 'Warning',
    filePath: this.filePath,
    text: 'Unnecessary whitespace in next-power-of-2 expander',
    range: this.rangeFromLocation(yy_.yylloc)
  });
 
break;
case 63 : 
/*! Conditions:: next_power_of_2 next_power_of_2_plus_1 */ 
/*! Rule::       [^ \t\d]|$ */ 
 
  throw new CsoundPreprocessorError({
    type: 'Error',
    filePath: this.filePath,
    text: 'Expected integer',
    range: this.rangeFromPosition(yy_.yylloc.first_line, yy_.yylloc.first_column)
  });
 
break;
case 64 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       \{ */ 
 
  if (lexer.isScorePreprocessor) {
    this.macro = {body: ''};
    this.startRanges.push(this.rangeFromLocation(yy_.yylloc));
    this.begin('score_loop');
    this.begin('score_loop_after_left_brace');
  } else {
    this.addText(yy_.yytext);
  }
 
break;
case 65 : 
/*! Conditions:: score_loop_after_left_brace */ 
/*! Rule::       [1-9]\d* */ 
 
  this.macro.repeatCount = Number(yy_.yytext);
  this.popState();
  this.begin('score_loop_after_repeat_count');
 
break;
case 66 : 
/*! Conditions:: score_loop_after_left_brace */ 
/*! Rule::       \s+ */ 
 // Do nothing 
break;
case 67 : 
/*! Conditions:: score_loop_after_left_brace */ 
/*! Rule::       .|{newline} */ 
 
  throw new CsoundPreprocessorError({
    type: 'Error',
    filePath: this.filePath,
    text: 'Expected integer greater than 0',
    range: this.rangeFromPosition(yy_.yylloc.first_line, yy_.yylloc.first_column)
  });
 
break;
case 68 : 
/*! Conditions:: score_loop_after_repeat_count */ 
/*! Rule::       {identifier} */ 
 
  this.macro.repititionMacro = {name: yy_.yytext};
  this.popState();
  this.begin('score_loop_after_repitition_macro_name');
 
break;
case 69 : 
/*! Conditions:: score_loop_after_repeat_count */ 
/*! Rule::       {newline} */ 
 this.popState(); 
break;
case 70 : 
/*! Conditions:: score_loop_after_repeat_count */ 
/*! Rule::       \s+ */ 
 // Do nothing 
break;
case 71 : 
/*! Conditions:: score_loop_after_repeat_count */ 
/*! Rule::       . */ 
 
  throw new CsoundPreprocessorError({
    type: 'Error',
    filePath: this.filePath,
    text: 'Expected macro name',
    range: this.rangeFromPosition(yy_.yylloc.first_line, yy_.yylloc.first_column)
  });
 
break;
case 72 : 
/*! Conditions:: score_loop_after_repitition_macro_name */ 
/*! Rule::       {newline} */ 
 this.popState(); 
break;
case 73 : 
/*! Conditions:: score_loop_after_repitition_macro_name */ 
/*! Rule::       \s+ */ 
 // Do nothing 
break;
case 74 : 
/*! Conditions:: score_loop_after_repitition_macro_name */ 
/*! Rule::       . */ 
 
  throw new CsoundPreprocessorError({
    type: 'Error',
    filePath: this.filePath,
    text: 'Expected newline',
    range: this.rangeFromPosition(yy_.yylloc.first_line, yy_.yylloc.first_column)
  });
 
break;
case 75 : 
/*! Conditions:: score_loop inner_score_loop */ 
/*! Rule::       \{ */ 
 
  this.macro.body += yy_.yytext;
  this.begin('inner_score_loop');
 
break;
case 76 : 
/*! Conditions:: score_loop */ 
/*! Rule::       \} */ 
 
  const repititionMacro = this.macro.repititionMacro;
  for (let repitition = 1; repitition <= this.macro.repeatCount; repitition++) {
    this.macroUse = new MacroUseElement(this.macro);
    if (repititionMacro) {
      repititionMacro.body = repitition.toString();
      this.macroUse.macrosByName[repititionMacro.name] = repititionMacro;
    }
    this.expandMacro(YY_START);
  }
  this.startRanges.pop();
  this.popState();
 
break;
case 77 : 
/*! Conditions:: inner_score_loop */ 
/*! Rule::       \} */ 
 
  this.macro.body += yy_.yytext;
  this.popState();
 
break;
case 78 : 
/*! Conditions:: score_loop inner_score_loop */ 
/*! Rule::       .|{newline} */ 
 this.macro.body += yy_.yytext; 
break;
case 79 : 
/*! Conditions:: score_loop inner_score_loop */ 
/*! Rule::       $ */ 
 
  this.messages.push({
    type: 'Error',
    filePath: this.filePath,
    text: `Missing terminating ${this.quote('}')}`,
    range: this.startRanges.pop()
  });
 
break;
case 80 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       {newline} */ 
 this.addNewline(); 
break;
case 81 : 
/*! Conditions:: else_true ifdef_true ifndef_directive ifdef_directive undef_directive macro_body before_macro_body define_directive INITIAL */ 
/*! Rule::       . */ 
 this.addText(yy_.yytext); 
break;
default:
  return this.simpleCaseActionClusters[$avoiding_name_collisions];
}
},
simpleCaseActionClusters: {

},
rules: [
/^(?:(\\[\t ]*(?:;.*)?(?:(?:\n|\r\n?))))/,
/^(?:\/\*)/,
/^(?:\/\*)/,
/^(?:\*\/)/,
/^(?:.|((?:\n|\r\n?)))/,
/^(?:$)/,
/^(?:((?:;|\/\/).*(?:(?:(?:\n|\r\n?))|$)))/,
/^(?:\\[^"\\abfnrtv])/,
/^(?:")/,
/^(?:\\.|[^$"\n\r])/,
/^(?:")/,
/^(?:((?:\n|\r\n?))|$)/,
/^(?:\{\{)/,
/^(?:(?:[^}]|\}[^}])+)/,
/^(?:\}\})/,
/^(?:$)/,
/^(?:(\$(?:[A-Z_a-z]\w*)\.?)\()/,
/^(?:[^'#)]+)/,
/^(?:\))/,
/^(?:(\$(?:[A-Z_a-z]\w*)\.?))/,
/^(?:(#[\t ]*(?:define)))/,
/^(?:([A-Z_a-z]\w*)\(?)/,
/^(?:\s+)/,
/^(?:([A-Z_a-z]\w*))/,
/^(?:\))/,
/^(?:\s+)/,
/^(?:.)/,
/^(?:$)/,
/^(?:['#])/,
/^(?:\))/,
/^(?:\s+)/,
/^(?:.)/,
/^(?:#)/,
/^(?:\s+)/,
/^(?:[^#]|$)/,
/^(?:(\\#|[^#])+)/,
/^(?:#)/,
/^(?:$)/,
/^(?:((?:#undef)))/,
/^(?:([A-Z_a-z]\w*))/,
/^(?:(#ifn?(?:def)))/,
/^(?:([A-Z_a-z]\w*))/,
/^(?:([A-Z_a-z]\w*))/,
/^(?:(#end(?:if)?\b))/,
/^(?:(#else))/,
/^(?:(#else))/,
/^(?:(#else))/,
/^(?:.|((?:\n|\r\n?)))/,
/^(?:$)/,
/^(?:(#end(?:if)?\b))/,
/^(?:(#else))/,
/^(?:((?:#include)))/,
/^(?:[ \t])/,
/^(?:[^ \t])/,
/^(?:((?:\n|\r\n?))|$)/,
/^(?:\s+)/,
/^(?:[^\s])/,
/^(?:$)/,
/^(?:@)/,
/^(?:@)/,
/^(?:\d+)/,
/^(?:\d+)/,
/^(?:[ \t]+)/,
/^(?:[^ \t\d]|$)/,
/^(?:\{)/,
/^(?:[1-9]\d*)/,
/^(?:\s+)/,
/^(?:.|((?:\n|\r\n?)))/,
/^(?:([A-Z_a-z]\w*))/,
/^(?:((?:\n|\r\n?)))/,
/^(?:\s+)/,
/^(?:.)/,
/^(?:((?:\n|\r\n?)))/,
/^(?:\s+)/,
/^(?:.)/,
/^(?:\{)/,
/^(?:\})/,
/^(?:\})/,
/^(?:.|((?:\n|\r\n?)))/,
/^(?:$)/,
/^(?:((?:\n|\r\n?)))/,
/^(?:.)/
],
conditions: {
  "inner_score_loop": {
    rules: [
      75,
      77,
      78,
      79
    ],
    inclusive: false
  },
  "score_loop_after_repitition_macro_name": {
    rules: [
      72,
      73,
      74
    ],
    inclusive: false
  },
  "score_loop_after_repeat_count": {
    rules: [
      68,
      69,
      70,
      71
    ],
    inclusive: false
  },
  "score_loop_after_left_brace": {
    rules: [
      65,
      66,
      67
    ],
    inclusive: false
  },
  "score_loop": {
    rules: [
      75,
      76,
      78,
      79
    ],
    inclusive: false
  },
  "next_power_of_2_plus_1": {
    rules: [
      61,
      62,
      63
    ],
    inclusive: false
  },
  "next_power_of_2": {
    rules: [
      59,
      60,
      62,
      63
    ],
    inclusive: false
  },
  "after_macro_parameter_value": {
    rules: [
      18,
      28,
      29
    ],
    inclusive: false
  },
  "macro_parameter_value_list": {
    rules: [
      17,
      24,
      58
    ],
    inclusive: false
  },
  "include_directive": {
    rules: [
      52,
      53,
      54
    ],
    inclusive: false
  },
  "else_false": {
    rules: [
      43,
      44,
      47,
      48
    ],
    inclusive: false
  },
  "else_true": {
    rules: [
      1,
      6,
      8,
      12,
      20,
      38,
      40,
      43,
      44,
      48,
      49,
      50,
      51,
      64,
      80,
      81
    ],
    inclusive: true
  },
  "ifdef_false": {
    rules: [
      43,
      46,
      47,
      48
    ],
    inclusive: false
  },
  "ifdef_true": {
    rules: [
      1,
      6,
      8,
      12,
      20,
      38,
      40,
      43,
      45,
      48,
      49,
      50,
      51,
      64,
      80,
      81
    ],
    inclusive: true
  },
  "ifndef_directive": {
    rules: [
      1,
      6,
      8,
      12,
      20,
      38,
      40,
      42,
      49,
      50,
      51,
      55,
      56,
      57,
      64,
      80,
      81
    ],
    inclusive: true
  },
  "ifdef_directive": {
    rules: [
      1,
      6,
      8,
      12,
      20,
      38,
      40,
      41,
      49,
      50,
      51,
      55,
      56,
      57,
      64,
      80,
      81
    ],
    inclusive: true
  },
  "undef_directive": {
    rules: [
      1,
      6,
      8,
      12,
      20,
      38,
      39,
      40,
      49,
      50,
      51,
      55,
      56,
      57,
      64,
      80,
      81
    ],
    inclusive: true
  },
  "macro_body": {
    rules: [
      1,
      6,
      8,
      12,
      20,
      35,
      36,
      37,
      38,
      40,
      49,
      50,
      51,
      64,
      80,
      81
    ],
    inclusive: true
  },
  "before_macro_body": {
    rules: [
      1,
      6,
      8,
      12,
      20,
      32,
      33,
      34,
      38,
      40,
      49,
      50,
      51,
      64,
      80,
      81
    ],
    inclusive: true
  },
  "after_macro_parameter_name_separator": {
    rules: [
      23,
      25,
      26
    ],
    inclusive: false
  },
  "after_macro_parameter_name": {
    rules: [
      28,
      29,
      30,
      31
    ],
    inclusive: false
  },
  "macro_parameter_name_list": {
    rules: [
      23,
      24,
      25,
      26,
      27
    ],
    inclusive: false
  },
  "define_directive": {
    rules: [
      1,
      6,
      8,
      12,
      20,
      21,
      22,
      38,
      40,
      49,
      50,
      51,
      55,
      56,
      57,
      64,
      80,
      81
    ],
    inclusive: true
  },
  "braced_string": {
    rules: [
      7,
      13,
      14,
      15
    ],
    inclusive: false
  },
  "quoted_string": {
    rules: [
      0,
      7,
      9,
      10,
      11,
      16,
      19
    ],
    inclusive: false
  },
  "block_comment": {
    rules: [
      2,
      3,
      4,
      5
    ],
    inclusive: false
  },
  "INITIAL": {
    rules: [
      0,
      1,
      6,
      8,
      12,
      16,
      19,
      20,
      38,
      40,
      49,
      50,
      51,
      58,
      64,
      80,
      81
    ],
    inclusive: true
  }
}
};

const fs = require('fs');
const path = require('path');

lexer.addNewline = (function() {
  this.appendToCurrentTextNode('\n');
  this.generatedLineCount++;
  this.generatedColumnCount = 0;
}).bind(lexer);

lexer.addText = (function(text) {
  this.appendToCurrentTextNode(text);
  this.generatedColumnCount += text.length;
}).bind(lexer);

lexer.appendToCurrentTextNode = (function(text) {
  this.sourceMap.add(
    [this.yylloc.first_line - 1, this.yylloc.first_column],
    [this.generatedLineCount, this.generatedColumnCount]
  );
  if (this.currentTextNode) {
    this.currentTextNode.text += text;
  } else {
    this.currentTextNode = new CsoundPreprocessorTextNode(text);
    this.rootElement.childNodes.push(this.currentTextNode);
  }
}).bind(lexer);

lexer.expandMacro = (function(YY_START) {
  const macrosByName = this.macroUse.macrosByName;
  const macro = this.macroUse.macro;
  if (macro.parameterNames && Object.keys(macrosByName).length < macro.parameterNames.length) {
    throw new CsoundPreprocessorError({
      type: 'Error',
      filePath: this.filePath,
      text: 'Too few arguments provided to function-like macro',
      range: lexer.rangeFromPosition(this.yylloc.first_line, this.yylloc.first_column),
      trace: [{
        type: 'Trace',
        filePath: this.filePath,
        text: `Macro ${this.quote(macro.name)} defined here`,
        range: macro.range
      }]
    });
  }
  const preprocessor = this.makePreprocessor(macro.body);
  preprocessor.filePath = this.filePath;
  preprocessor.isScorePreprocessor = this.isScorePreprocessor;
  Object.assign(preprocessor.macrosByName, macrosByName);
  try {
    preprocessor.lex();
  } catch (error) {
    if (error.lintMessage)
      error.lintMessage.range = this.macroUse.range;
    throw(error);
  }
  this.macroUse.childNodes = preprocessor.rootElement.childNodes;
  this.rootElement.childNodes.push(this.macroUse);
  this.currentTextNode = null;
  if ('quoted_string' === YY_START) {
    this.messages.push({
      type: 'Warning',
      filePath: this.filePath,
      text: `${this.quote(macro.name)} macro expanded in string`,
      range: this.rangeFromLocation(this.yylloc)
    });
  }
}).bind(lexer);

lexer.getMacro = (function(macroName) {
  const macro = this.macrosByName[macroName];
  if (!macro) {
    throw new CsoundPreprocessorError({
      type: 'Error',
      filePath: this.filePath,
      text: `${this.quote(macroName)} is not a macro or macro parameter`,
      range: this.rangeFromLocation(this.yylloc)
    });
  }
  return macro;
}).bind(lexer);

lexer.getOutput = (function() {
  return this.rootElement.getOutput();
}).bind(lexer);

const original_lex = lexer.lex;
lexer.lex = (function() {
  const token = original_lex.apply(this, arguments);
  if (this.done) {
    this.sourceMap.add(
      [this.yylloc.first_line - 1, this.yylloc.first_column + 1],
      [this.generatedLineCount, this.generatedColumnCount]
    );
  }
  return token;
}).bind(lexer);

lexer.makePreprocessor = (function(input) {
  // A function like yy_scan_string is not available in jison-lex. Instead,
  // this function creates a new preprocessor, taking care to avoid getting the
  // current preprocessor in the Node.js module cache.
  delete require.cache[__filename];
  const preprocessor = require(__filename);
  preprocessor.setInput(input);
  Object.assign(preprocessor.macrosByName, this.macrosByName);
  return preprocessor;
}).bind(lexer);

lexer.maximumIncludeDepth = 100;

lexer.quote = string => `‘${string}’`;

lexer.rangeFromLocation = yylloc => {
  return [
    [yylloc.first_line - 1, yylloc.first_column],
    [yylloc.last_line - 1, yylloc.last_column]
  ];
};

lexer.rangeFromPosition = (line, column) => {
  const lineMinus1 = line - 1;
  return [[lineMinus1, column], [lineMinus1, column]];
};

const original_setInput = lexer.setInput;
lexer.setInput = (function(input, yy) {
  this.currentTextNode = null;
  this.includeDepth = 0;
  this.generatedColumnCount = 0;
  this.generatedLineCount = 0;
  // From cs_init_math_constants_macros in
  // https://github.com/csound/csound/blob/develop/Engine/csound_pre.lex
  this.macrosByName = {
    M_E:        {name: 'M_E',        body: '2.71828182845904523536'},
    M_LOG2E:    {name: 'M_LOG2E',    body: '1.44269504088896340736'},
    M_LOG10E:   {name: 'M_LOG10E',   body: '0.43429448190325182765'},
    M_LN2:      {name: 'M_LN2',      body: '0.69314718055994530942'},
    M_LN10:     {name: 'M_LN10',     body: '2.30258509299404568402'},
    M_PI:       {name: 'M_PI',       body: '3.14159265358979323846'},
    M_PI_2:     {name: 'M_PI_2',     body: '1.57079632679489661923'},
    M_PI_4:     {name: 'M_PI_4',     body: '0.78539816339744830962'},
    M_1_PI:     {name: 'M_1_PI',     body: '0.31830988618379067154'},
    M_2_PI:     {name: 'M_2_PI',     body: '0.63661977236758134308'},
    M_2_SQRTPI: {name: 'M_2_SQRTPI', body: '1.12837916709551257390'},
    M_SQRT2:    {name: 'M_SQRT2',    body: '1.41421356237309504880'},
    M_SQRT1_2:  {name: 'M_SQRT1_2',  body: '0.70710678118654752440'},
    M_INF:      {name: 'M_INF',      body: '800000000000.0'}
  };
  this.messages = [];
  this.rootElement = new CsoundPreprocessorElement();
  this.sourceMap = new SourceMap();
  this.startRanges = [];
  return original_setInput.apply(this, arguments);
}).bind(lexer);

class CsoundPreprocessorTextNode {
  constructor(text) {
    this.text = text;
  }

  getOutput() {
    return this.text;
  }
}

class CsoundPreprocessorElement {
  constructor() {
    this.childNodes = [];
  }

  getOutput() {
    let output = '';
    for (const childNode of this.childNodes) {
      output += childNode.getOutput();
    }
    return output;
  }
}

class MacroUseElement extends CsoundPreprocessorElement {
  constructor(macro) {
    super();
    this.macro = macro;
    this.macrosByName = {};
  }
}

// The LineMap and SourceMap classes are based on code in CoffeeScript
// <http://coffeescript.org/documentation/docs/sourcemap.html>, which is
// MIT-licensed <https://github.com/jashkenas/coffeescript/blob/master/LICENSE>.

class LineMap {
  constructor(line) {
    this.line = line;
    this.columnMaps = [];
  }

  add(column, sourceLocation) {
    this.columnMaps[column] = {
      line: this.line,
      column: column,
      sourceLine: sourceLocation[0],
      sourceColumn: sourceLocation[1]
    };
  }

  sourceLocation(column) {
    for ( ; column >= 0; column--) {
      const map = this.columnMaps[column];
      if (map)
        return [map.sourceLine, map.sourceColumn];
    }
    return null;
  }
}

class SourceMap {
  constructor(line) {
    this.lineMaps = [];
  }

  add(sourceLocation, generatedLocation) {
    const line = generatedLocation[0];
    let lineMap = this.lineMaps[line];
    if (!lineMap) {
      lineMap = new LineMap(line);
      this.lineMaps[line] = lineMap;
    }
    lineMap.add(generatedLocation[1], sourceLocation);
  }

  sourceLocation(location) {
    for (let line = location[0]; line >= 0; line--) {
      const lineMap = this.lineMaps[line];
      if (lineMap)
        return lineMap.sourceLocation(location[1]);
    }
    return null;
  }

  sourceRange(range) {
    return [this.sourceLocation(range[0]), this.sourceLocation(range[1])];
  }
}

class CsoundPreprocessorError extends Error {
  constructor(lintMessage) {
    super(lintMessage.text);
    this.name = 'CsoundPreprocessorError';
    this.lintMessage = lintMessage;
  }
}

module.exports = lexer;
return lexer;
})();