name: CI

on: [push, pull_request]

jobs:
  Test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Boost and Csound on macOS
      run: brew install boost csound
      if: ${{ matrix.os == 'macos-latest' }}
    - name: Install Boost and Csound on Linux
      run: |
        sudo apt-get --assume-yes install libboost-dev libsndfile1-dev
        wget --no-verbose https://github.com/csound/csound/archive/refs/tags/6.18.1.tar.gz
        tar -xf 6.18.1.tar.gz
        cd csound-6.18.1
        cmake -S . -B build -DBUILD_DSSI_OPCODES=OFF
        cmake --build build
        sudo cmake --install build
        sudo ldconfig
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Install linter-csound on macOS
      run: |
        export CPATH="$(brew --prefix)/include"
        export LIBRARY_PATH="$(brew --prefix)/lib"
        npm install
      if: ${{ matrix.os == 'macos-latest' }}
    - name: Install linter-csound on Linux
      run: npm install
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Install Jasmine
      run: npm install --global jasmine@3

    - name: Run tests
      run: |
        cd lib/csound-parser
        jasmine
