name: CI

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Boost and Csound
      run: brew install boost csound

    - name: Install linter-csound
      run: npm install

    - name: Install Jasmine
      run: npm install --global jasmine

    - name: Run tests
      run: |
        cd lib/csound-parser
        jasmine

  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1

    - name: Build and install Csound
      run: |
        sudo apt-get --assume-yes install bison flex libsndfile1-dev
        wget --no-verbose https://github.com/csound/csound/archive/6.15.0.tar.gz
        tar -xf 6.15.0.tar.gz
        cd csound-6.15.0
        mkdir build
        cd build
        cmake .. -DBUILD_DSSI_OPCODES=OFF
        make
        sudo make install
        sudo ldconfig

    - name: Install Boost
      run: sudo apt-get --assume-yes install libboost-dev

    - name: Install linter-csound
      run: npm install

    - name: Install Jasmine
      run: npm install --global jasmine

    - name: Run tests
      run: |
        cd lib/csound-parser
        jasmine

  Windows:
    runs-on: windows-2016
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Csound
      run: |
        curl.exe --location --remote-name --remote-header-name --show-error --silent https://github.com/csound/csound/releases/download/6.15.0/csound-windows_x86_64-6.15.0-installer.exe
        Start-Process csound-windows_x86_64-6.15.0-installer.exe '/verySilent /noRestart' -Wait
        Write-Output "::add-path::$Env:ProgramFiles\Csound6_x64\bin"

    - name: Install linter-csound
      run: |
        $Env:CL = "/I`"$Env:BOOST_ROOT_1_72_0\include`" /I`"$Env:ProgramFiles\Csound6_x64\include`""
        $Env:LINK = "`"$Env:ProgramFiles\Csound6_x64\lib\csound64.lib`""
        npm install

    - name: Install Jasmine
      run: npm install --global jasmine

    - name: Run tests
      run: |
        cd lib\csound-parser
        jasmine
